
[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x969896"
blue = "0xb4b7b4"
cyan = "0xa3685a"
green = "0x282a2e"
magenta = "0xe0e0e0"
red = "0xde935f"
white = "0xffffff"
yellow = "0x373b41"

[colors.cursor]
cursor = "0xc5c8c6"
text = "0x1d1f21"

[colors.normal]
black = "0x1d1f21"
blue = "0x81a2be"
cyan = "0x8abeb7"
green = "0xb5bd68"
magenta = "0xb294bb"
red = "0xcc6666"
white = "0xc5c8c6"
yellow = "0xf0c674"

[colors.primary]
background = "0x1d1f21"
foreground = "0xc5c8c6"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "OFF"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 14.0

[font.bold]
family = "Iosevka Term"
style = "Medium"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Iosevka Term"
style = "Light Italic"

[font.normal]
family = "Iosevka Term"
style = "Light"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 0
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[terminal.shell]
args = ["-l", "-c", "/usr/local/bin/tmux attach || /usr/local/bin/tmux new -s main"]
program = "bash"

[window]
decorations = "none"
dynamic_padding = true
startup_mode = "Fullscreen"

[window.padding]
x = 10
y = 5

[general]
live_config_reload = true

[terminal]
